kind: workflow
id: ""
name: marketing-analyst
description: "You are a marketing analyst. Given a product category, continuously discover and validate profitable ecommerce products advertised in the United States (active for >=3 months), then screen for low competitive density in Australia using Ads Library connected via MCP, and output one best 'copy-to-AU' product in a strict machine-consumable format backed by real, cited figures. Process pipeline: plan keywords -> discover ads -> enrich product info (parallel foreach) -> profile product vendors (parallel foreach) -> estimate demand and competition (parallel foreach) -> score candidates."
trigger:
  kind: OnConversationStart
  id: trigger_wf
  variables:
    enrichedCandidateAggregate: []
    vendorProfilesAggregate: []
    validatedCandidatesAggregate: []
  actions:
    - kind: InvokeAzureAgent
      id: plan-keywords
      agent:
        name: plan-keywords
      description: The agent correspond to the "plan keywords" stage in process pipeline, and be responsible for planning optimized keywords for ad discovery based on the input product category and optional seed keywords, and outputting the optimized keyword list for downstream ad discovery.
      conversationId: =System.ConversationId
      input:
        messages: =pet products
      output:
        autoSend: true
        responseObject: Local.OPTIMIZED_KEYWORDS
    - kind: InvokeAzureAgent
      id: discover-ads
      agent:
        name: discover-ads
      description: The agent correspond to the "discover ads" stage in process pipeline, and be responsible for discovering pet-product ads targeting the United States and outputting raw, normalized ad records for downstream filtering.
      conversationId: =System.ConversationId
      input:
        messages: =Local.OPTIMIZED_KEYWORDS
      output:
        autoSend: true
        responseObject: Local.RAW_AD_SET
    - kind: ForEach
      id: enrich-foreach
      foreach: =Local.RAW_AD_SET.raw_ads
      itemName: adItem
      actions:
        - kind: InvokeAzureAgent
          id: enrich-product-info-item
          agent:
            name: enrich-product-info
          conversationId: =System.ConversationId
          input:
            messages: =Local.enrich-foreach.adItem
          output:
            autoSend: true
            responseObject: Local.ENRICHED_ITEM
        - kind: SetVariable
          id: aggregate-enriched-candidate
          variableName: enrichedCandidateAggregate
          value: =Local.enrichedCandidateAggregate + [Local.ENRICHED_ITEM]
    - kind: SetVariable
      id: assign-enriched-candidates
      variable: ENRICHED_CANDIDATE_SET
      value: =Local.enrichedCandidateAggregate
    - kind: ForEach
      id: profile-foreach
      foreach: =Local.ENRICHED_CANDIDATE_SET
      itemName: candidate
      actions:
        - kind: InvokeAzureAgent
          id: profile-vendor-item
          agent:
            name: profile-product-vendors
          conversationId: =System.ConversationId
          input:
            messages: =Local.profile-foreach.candidate
          output:
            autoSend: true
            responseObject: Local.PROFILED_CANDIDATE
        - kind: SetVariable
          id: append-vendor-profile
          variableName: vendorProfilesAggregate
          value: =Local.vendorProfilesAggregate + [Local.PROFILED_CANDIDATE]
    - kind: SetVariable
      id: assign-vendor-candidates
      variable: VENDOR_PROFILED_SET
      value: =Local.vendorProfilesAggregate
    - kind: ForEach
      id: estimate-foreach
      foreach: =Local.VENDOR_PROFILED_SET
      itemName: validatedCandidateItem
      actions:
        - kind: InvokeAzureAgent
          id: estimate-demand-competition-item
          agent:
            name: estimate-demand-and-competition
          conversationId: =System.ConversationId
          input:
            messages: =Local.estimate-foreach.validatedCandidateItem
          output:
            autoSend: true
            responseObject: Local.VALIDATED_ITEM
        - kind: SetVariable
          id: append-validated-item
          variableName: validatedCandidatesAggregate
          value: =Local.validatedCandidatesAggregate + [Local.VALIDATED_ITEM]
    - kind: SetVariable
      id: assign-validated-candidates
      variable: VALIDATED_CANDIDATE_SET
      value: =Local.validatedCandidatesAggregate
    - kind: InvokeAzureAgent
      id: score-candidates
      agent:
        name: score-candidates
      conversationId: =System.ConversationId
      description: The agent correspond to the "score candidates" stage in process pipeline, and be responsible for scoring the validated candidate set and outputting the final winner in a strict machine-consumable format backed by real, cited figures.
      input:
        messages: =Local.VALIDATED_CANDIDATE_SET
      output:
        autoSend: true
        responseObject: Local.FINAL_WINNER_PACKET
    - kind: SendActivity
      activity: Local.FINAL_WINNER_PACKET
      id: node-1771389676430
